version: "3"
services:
  cache:
    image: redis:6

  directus:
    image: awr-ggl/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
    depends_on:
      - cache
    # Environment variables can also be defined in a file (for example `.env`):
    env_file:
      - .env
