name: CMS Development Deployment

on:
  push:
    branches: [ development ]
env:
  CHANGE_DIR: cd ${{ secrets.DIRECTORY_PATH }};

jobs:
  dev:
    runs-on: self-hosted
    name: Deploy Development
    steps:
      - name: Git Pull
        run: ${{ env.CHANGE_DIR }} sudo git fetch origin; sudo git checkout development && sudo git pull

      - name: Build Docker Image
        run: ${{ env.CHANGE_DIR }} sudo ./docker-build.sh

      - name: Restart Docker Container
        run: ${{ env.CHANGE_DIR }} sudo docker compose down && sudo docker compose up -d

      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
